export const SIGNUP_PENDING = 'SIGNUP_PENDING';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SET_USER = 'SET_USER';

export const LOGIN_PENDING = 'LOGIN_PENDING';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REQUEST_RESET_PENDING = 'REQUEST_RESET_PENDING';

export const REQUEST_RESET_FAILURE = 'REQUEST_RESET_FAILURE';

export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';

export const SIGNOUT_PENDING = 'SIGNUOUT_PENDING';

export const SIGNUOUT_SUCCESS = 'SIGNUOUT_SUCCESS';

export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';
