export const SIGNUP_PENDING = 'SIGNUP_PENDING';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SETUP_USER = 'SETUP_USER';

export const CLEAN_UP = 'CLEAN_UP';

export const LOGIN_PENDING = 'LOGIN_PENDING';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REQUEST_RESET_PENDING = 'REQUEST_RESET_PENDING';

export const REQUEST_RESET_FAILURE = 'REQUEST_RESET_FAILURE';

export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';
